### PR TITLE
Add more IBC related names

### PR DESCRIPTION
**Pull request by penso**
Adding a few missing type names implementations.

### CODE REVIEW

**Comment by tony-iqlusion** [comment]
Really we should switch to generating this automatically, now that it's possible

**Comment by penso** [comment]
> Really we should switch to generating this automatically, now that it's possible

Very much agree with this, as well as having serde added.

**Comment by penso** [comment]
> Really we should switch to generating this automatically, now that it's possible

Can you (re)give me pointers to adding this automatically? I might look at it at some point if no one has done it.

**Comment by tony-iqlusion** [comment]
@penso in `prost-build`, when we invoke `tonic_build::configure()`, it needs to be passed some additional configuration, which can be passed in by calling `.compile_with_config` rather than just `.compile`:

https://docs.rs/prost-build/latest/prost_build/struct.Config.html

The newly added `enable_type_names` option can do it:

https://docs.rs/prost-build/latest/prost_build/struct.Config.html#method.enable_type_names

**Pull request merged**
