### PR TITLE
Osmosis-Proto 

### PR DESCRIPTION
**Pull request by Philipp-Sc**
Hi, 

I just took the time to update the `osmosis-proto` crate. 

Note:

the folder `proto-build` now contains:
- `cosmos` (from `cosmos-rust/proto-build`)
- `osmosis` (from `cosmos-rust-development/proto-build-osmosis`)

Best regards,
Philipp

### CODE REVIEW

**Comment by Philipp-Sc** [comment]
@tony-iqlusion can you point me in the right direction, what is missing / what are the requirements for `osmosis-proto` to be merged?

**Comment by tony-iqlusion** [comment]
@Philipp-Sc looks close! Needs rustfmt.

The build on WASM is also failing. I don't think you need to build on WASM for an MVP. But if you don't plan on supporting it out-of-the-gate, you need to remove the CI jobs to test the WASM build.

**Comment by Philipp-Sc** [comment]
@tony-iqlusion thank you, I removed the WASM build target for now. I do not need it, but I am happy to help add it later if needed. I also fixed the formatting. I hope the workflows go through now.

**Comment by tony-iqlusion** [comment]
@Philipp-Sc it looks like the crate is failing to build without default features

**Comment by Philipp-Sc** [comment]
@tony-iqlusion thank you, I removed `--no-default-features` from the workflow, since the default feature is required.

Anyway you might not need to merge this PR after all. 

I found there is [osmosis-rust](https://github.com/osmosis-labs/osmosis-rust), their `README.md` does not mention anything about proto definitions. That's why I didn't find it before. They have a `proto-build` package.

**Comment by tony-iqlusion** [comment]
@Philipp-Sc interesting re `osmosis-rust`, let me open an issue to ask

**Comment by Philipp-Sc** [comment]
@tony-iqlusion feel free to close the PR. As long as the osmosis team maintains their `proto-build` package, I am happy with it. I will keep the fork for a while and later switch my project to the official package.

Anyway thank you for the time you took to go through this PR. It was a good exercise in improving my rust skills.

**Comment by Philipp-Sc** [comment]
@tony-iqlusion fyi I think will continue maintaining ```osmosis-proto```, for my use I prefer to have the same types generated for ```cosmos-sdk-proto``` and ```osmosis-proto```.

The official ```osmosis-std``` has quite [a few customizations and a somewhat different structure](https://docs.rs/osmosis-std/0.12.0/osmosis_std/). 

As long as I don't run into issues I will not migrate (my project [cosmos-rust-bot](https://github.com/Philipp-Sc/cosmos-rust-bot/tree/development/workspace/cosmos-rust-bot)) to ```osmosis-std```, with the goal to maintain and keep ```osmosis-proto``` as vanilla and close to `cosmos-sdk-proto` as possible.

**Comment by tony-iqlusion** [comment]
@Philipp-Sc ok, perhaps you can make a separate repo for it somewhere then?

I thought this was an interesting PR when I wasn't aware of a separate official Osmosis Rust project, but since there is I'd prefer not to have a "competing" implementation here, even if it better interops with the crates in this repo.

**Comment by Philipp-Sc** [comment]
I agree, just wanted to give an update on this. Closing this PR now. Thanks for all your help.

Best regards,
Philipp

**Pull request closed without merging**
