### PR TITLE
feat: Support for wasmd >=0.29 by generating files via buf

### PR DESCRIPTION
**Pull request by apollo-sturdy**
Since `wasmd` >= 0.29 started using buf, it broke `proto-build`. This PR fixes it by instead generating the files via [buf](https://buf.build/). Needless to say this changes requires users to have buf installed. See here for more context: https://github.com/cosmos/cosmos-rust/issues/318#issuecomment-1443670490

### CODE REVIEW

**Comment by tony-iqlusion** [comment]
@apollo-sturdy can you rebase? that should take care of the MSRV issues

**Comment by apollo-sturdy** [comment]
> @apollo-sturdy can you rebase? that should take care of the MSRV issues

Done!

**Comment by tony-iqlusion** [comment]
Looks like `cosmrs` needs to be updated due to the schema changes.

@apollo-sturdy not sure if you want to take that on or not. If not, I can

**Comment by apollo-sturdy** [comment]
> Looks like `cosmrs` needs to be updated due to the schema changes.
> 
> @apollo-sturdy not sure if you want to take that on or not. If not, I can

Would be great if you could do it. I'm not too familiar with it or the main Cosmos SDK types as I mostly work with CosmWasm.

**Comment by tony-iqlusion** [comment]
Merged in #358

**Pull request closed without merging**
