### PR TITLE
bump tendermint-rs crates to 0.26

### PR DESCRIPTION
**Pull request by tomtau**

### CODE REVIEW

**Comment by tony-iqlusion** [comment]
Looks like this needs an MSRV bump

**Comment by tony-iqlusion** [comment]
Guess we should bump to v0.26 actually? 😅

https://github.com/informalsystems/tendermint-rs/pull/1218

**Comment by tomtau** [comment]
@tony-iqlusion 0.26 was just released, so bumped to it

**Comment by tony-iqlusion** [comment]
@tomtau looks like some code changes are required.

I can take a look unless you want to do it.

I also think we might be able to relax the version requirements? Need to double check with @thanethomson

**Comment by tony-iqlusion** [comment]
Closing in favor of #302

**Pull request closed without merging**
