### PR TITLE
Revert "Run `proto-build` automatically with GitHub Actions (#24)"

### PR DESCRIPTION
**Pull request by tony-iqlusion**
This reverts commit 95371cf40d5432194c2201037bddc90d610ec96f.

Per #62 it appears `prost-build` generates files with a somewhat nondeterministic ordering, triggering spurious PRs even when nothing is changed.

For an auto-rebuild to be helpful the build needs to be fully deterministic.

### CODE REVIEW

**Comment by tony-iqlusion** [comment]
Closing this due to the non-determinism (see also #65)

**Review by jkilpatr — APPROVED** [review]
That's very annoying. Could we maybe just flag the task to run on changes to the cosmos-sdk-proto folder? I'm not sure it's worth the effort and will defer to you on that.

**Comment by tony-iqlusion** [comment]
That's an interesting suggestion and might resolve some of the problems

**Comment by tony-iqlusion** [comment]
Will open another PR that scopes when this action runs

**Pull request closed without merging**
