### PR TITLE
WASM support with grpc-web

### PR DESCRIPTION
**Pull request by shravanshetty1**

### CODE REVIEW

**Comment by shravanshetty1** [comment]
@tony-iqlusion seems to work for grpc and grpc-web

**Comment by tony-iqlusion** [comment]
I'd like to bump `prost` and `tonic` before attempting this, but we're stuck waiting for tendermint-rs to update.

**Comment by romac** [comment]
We can't update to `prost` 0.8 in tendermint-rs at the moment because `Prost` 0.8 includes a number of regressions which affect the generated code, notably https://github.com/tokio-rs/prost/issues/502 / https://github.com/tokio-rs/prost/issues/490.

**Comment by shravanshetty1** [comment]
was away for last few days - will try to get this done soon

**Comment by tony-iqlusion** [comment]
If need be we can make another breaking release to get this in. 

It would be nice to fix #151 but it requires a breaking change as well.

**Comment by shravanshetty1** [comment]
@tony-iqlusion 

I pulled the latest changes and rebuilt the proto files from current `main` branch and I am getting extra code that should not exist.

To generate the files, I navigated to the `proto-build` and ran the command `cargo run`.
Ideally no files should have been modified since the commit should have the latest changes but for me 4 files had changed.

```
➜  cosmos-sdk-proto git:(main) ✗ git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   src/prost/cosmos.bank.v1beta1.rs
        modified:   src/prost/cosmos.base.store.v1beta1.rs
        modified:   src/prost/cosmos.evidence.v1beta1.rs
        modified:   src/prost/cosmos.staking.v1beta1.rs
```

I ran `cargo check` in `cosmos-sdk-proto` to check if the generated files are valid and they were not compiling.

```
➜  cosmos-sdk-proto git:(main) ✗ cargo check
    Checking cosmos-sdk-proto v0.8.0 (/home/anon/projects/cosmos/cosmos-rust/cosmos-sdk-proto)
error[E0428]: the name `Validators` is defined multiple times
   --> cosmos-sdk-proto/src/prost/cosmos.staking.v1beta1.rs:550:5
    |
544 |     pub struct Validators {
    |     --------------------- previous definition of the type `Validators` here
...
550 |     pub enum Validators {
    |     ^^^^^^^^^^^^^^^^^^^ `Validators` redefined here
    |
    = note: `Validators` must be defined only once in the type namespace of this module

error[E0119]: conflicting implementations of trait `std::clone::Clone` for type `cosmos::staking::v1beta1::stake_authorization::Validators`
   --> cosmos-sdk-proto/src/prost/cosmos.staking.v1beta1.rs:549:14
    |
543 |     #[derive(Clone, PartialEq, ::prost::Message)]
    |              ----- first implementation here
...
549 |     #[derive(Clone, PartialEq, ::prost::Oneof)]
    |              ^^^^^ conflicting implementation for `cosmos::staking::v1beta1::stake_authorization::Validators`
    |
    = note: this error originates in the derive macro `Clone` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0119]: conflicting implementations of trait `std::cmp::PartialEq` for type `cosmos::staking::v1beta1::stake_authorization::Validators`
   --> cosmos-sdk-proto/src/prost/cosmos.staking.v1beta1.rs:549:21
    |
543 |     #[derive(Clone, PartialEq, ::prost::Message)]
    |                     --------- first implementation here
...
549 |     #[derive(Clone, PartialEq, ::prost::Oneof)]
    |                     ^^^^^^^^^ conflicting implementation for `cosmos::staking::v1beta1::stake_authorization::Validators`
    |
    = note: this error originates in the derive macro `PartialEq` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0119]: conflicting implementations of trait `std::marker::StructuralPartialEq` for type `cosmos::staking::v1beta1::stake_authorization::Validators`
   --> cosmos-sdk-proto/src/prost/cosmos.staking.v1beta1.rs:549:21
    |
543 |     #[derive(Clone, PartialEq, ::prost::Message)]
    |                     --------- first implementation here
...
549 |     #[derive(Clone, PartialEq, ::prost::Oneof)]
    |                     ^^^^^^^^^ conflicting implementation for `cosmos::staking::v1beta1::stake_authorization::Validators`
    |
    = note: this error originates in the derive macro `PartialEq` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0119]: conflicting implementations of trait `std::fmt::Debug` for type `cosmos::staking::v1beta1::stake_authorization::Validators`
   --> cosmos-sdk-proto/src/prost/cosmos.staking.v1beta1.rs:549:32
    |
543 |     #[derive(Clone, PartialEq, ::prost::Message)]
    |                                ---------------- first implementation here
...
549 |     #[derive(Clone, PartialEq, ::prost::Oneof)]
    |                                ^^^^^^^^^^^^^^ conflicting implementation for `cosmos::staking::v1beta1::stake_authorization::Validators`
    |
    = note: this error originates in the derive macro `::prost::Oneof` (in Nightly builds, run with -Z macro-backtrace for more info)

Some errors have detailed explanations: E0119, E0428.
For more information about an error, try `rustc --explain E0119`.
error: could not compile `cosmos-sdk-proto` due to 5 previous errors
```

Have you faced this issue before, and if you have how did you deal with it?

**Comment by tony-iqlusion** [comment]
@shravanshetty1 see #154. It's a naming conflict in the generated protos.

For now the only solution is hand-editing the generated code 😢

**Comment by shravanshetty1** [comment]
Ok finished and tested it seems to work in grpc-web and normal grpc. Made new PR due to ugly commit history on this one - https://github.com/cosmos/cosmos-rust/pull/157

**Pull request closed without merging**
